"""add date and time to tasks

Revision ID: 571d2f23e548
Revises: 
Create Date: 2026-06-11 14:54:14.873481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571d2f23e548'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('time')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
